language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++ qt4-qmake libqt4-dev qt5-qmake qtbase5-dev

script: 
  - qmake -qt=qt4 -v
  - qmake -qt=qt4
  - make
# - make -k check
  - make clean
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make
# - make -k check

notifications:
  email: false
